<a href="https://colab.research.google.com/github/ajaykumar-br/NLP-101/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## BOW, TF-IDF


In [ ]:
# !pip install nltk
import nltk

In [ ]:
paragraph="""
Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament. He is also the longest serving prime minister from a non-Congress party.

Born and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there. He was introduced to the RSS at age eight. He has drawn attention to having to work as a child in his father's tea stall on the Vadnagar railway station platform, a description that has not been reliably corroborated. At age 18, Modi was married to Jashodaben Chimanlal Modi, whom he abandoned soon after. He left his parental home where she had come to live. He first publicly acknowledged her as his wife more than four decades later when required to do so by Indian law, but has made no contact with her since. Modi has asserted he had travelled in northern India for two years after leaving his parental home, visiting a number of religious centres, but few details of his travels have emerged. Upon his return to Gujarat in 1971, he became a full-time worker for the RSS. After the state of emergency was declared by prime minister Indira Gandhi in 1975, Modi went into hiding. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[b]
"""

In [ ]:
paragraph

"\nNarendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation. He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament. He is also the longest serving prime minister from a non-Congress party.\n\nBorn and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there. He was introduced to the RSS at age eight. He has drawn attention to having to work 

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
## tokenization-- converts paragraph-sentences-words
nltk.download('punkt')
sentences=nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
print(sentences)

['\nNarendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014.', 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi.', 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer organisation.', "He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament.", 'He is also the longest serving prime minister from a non-Congress party.', 'Born and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there.', 'He was introduced to the RSS at age eight.', "He has drawn attention

In [ ]:
stemmer=PorterStemmer()

In [ ]:
stemmer.stem('history')

'histori'

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
lemmatizer=WordNetLemmatizer()

In [ ]:
lemmatizer.lemmatize('goes')

'go'

In [ ]:
len(sentences)

16

In [ ]:
import re

In [ ]:

corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    corpus.append(review)

In [ ]:
corpus

[' narendra damodardas modi  gujarati    n  end   d mod   d s  modi    listen   born    september       a  is an indian politician serving as the   th and current prime minister of india since      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament from varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer organisation ',
 'he is the first prime minister to have been born after india s independence in      and the second prime minister not belonging to the indian national congress to have won two consecutive majorities in the lok sabha  or the lower house of india s parliament ',
 'he is also the longest serving prime minister from a non congress party ',
 'born and raised in vadnagar  a small town in northeastern gujarat  modi completed his secondary education there ',
 'he was introduced to the rss at age eight ',
 'he has drawn att

In [ ]:
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
## stemming
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

narendra
damodarda
modi
gujarati
n
end
mod
modi
listen
born
septemb
indian
politician
serv
th
current
prime
minist
india
sinc
modi
chief
minist
gujarat
member
parliament
varanasi
member
bharatiya
janata
parti
bjp
rashtriya
swayamsevak
sangh
rss
right
wing
hindu
nationalist
paramilitari
volunt
organis
first
prime
minist
born
india
independ
second
prime
minist
belong
indian
nation
congress
two
consecut
major
lok
sabha
lower
hous
india
parliament
also
longest
serv
prime
minist
non
congress
parti
born
rais
vadnagar
small
town
northeastern
gujarat
modi
complet
secondari
educ
introduc
rss
age
eight
drawn
attent
work
child
father
tea
stall
vadnagar
railway
station
platform
descript
reliabl
corrobor
age
modi
marri
jashodaben
chimanl
modi
abandon
soon
left
parent
home
come
live
first
publicli
acknowledg
wife
four
decad
later
requir
indian
law
made
contact
sinc
modi
assert
travel
northern
india
two
year
leav
parent
home
visit
number
religi
centr
detail
travel
emerg
upon
return
gujarat
becam
full

In [ ]:
## lemmatization
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

narendra
damodardas
modi
gujarati
n
end
mod
modi
listen
born
september
indian
politician
serving
th
current
prime
minister
india
since
modi
chief
minister
gujarat
member
parliament
varanasi
member
bharatiya
janata
party
bjp
rashtriya
swayamsevak
sangh
r
right
wing
hindu
nationalist
paramilitary
volunteer
organisation
first
prime
minister
born
india
independence
second
prime
minister
belonging
indian
national
congress
two
consecutive
majority
lok
sabha
lower
house
india
parliament
also
longest
serving
prime
minister
non
congress
party
born
raised
vadnagar
small
town
northeastern
gujarat
modi
completed
secondary
education
introduced
r
age
eight
drawn
attention
work
child
father
tea
stall
vadnagar
railway
station
platform
description
reliably
corroborated
age
modi
married
jashodaben
chimanlal
modi
abandoned
soon
left
parental
home
come
live
first
publicly
acknowledged
wife
four
decade
later
required
indian
law
made
contact
since
modi
asserted
travelled
northern
india
two
year
leaving
pare

In [ ]:
## Apply Stopswords. Lemmatize
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['narendra damodardas modi gujarati n end mod modi listen born september indian politician serving th current prime minister india since',
 'modi chief minister gujarat member parliament varanasi',
 'member bharatiya janata party bjp rashtriya swayamsevak sangh r right wing hindu nationalist paramilitary volunteer organisation',
 'first prime minister born india independence second prime minister belonging indian national congress two consecutive majority lok sabha lower house india parliament',
 'also longest serving prime minister non congress party',
 'born raised vadnagar small town northeastern gujarat modi completed secondary education',
 'introduced r age eight',
 'drawn attention work child father tea stall vadnagar railway station platform description reliably corroborated',
 'age modi married jashodaben chimanlal modi abandoned soon',
 'left parental home come live',
 'first publicly acknowledged wife four decade later required indian law made contact since',
 'modi asserted 

In [ ]:
##Bag OF Words
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(binary=True,ngram_range=(2,3))

In [ ]:
X=cv.fit_transform(corpus)

In [ ]:
cv.vocabulary_

{'narendra damodardas': 176,
 'damodardas modi': 49,
 'modi gujarati': 168,
 'gujarati end': 84,
 'end mod': 63,
 'mod modi': 158,
 'modi listen': 170,
 'listen born': 128,
 'born september': 28,
 'september indian': 240,
 'indian politician': 110,
 'politician serving': 202,
 'serving th': 244,
 'th current': 260,
 'current prime': 47,
 'prime minister': 206,
 'minister india': 152,
 'india since': 103,
 'narendra damodardas modi': 177,
 'damodardas modi gujarati': 50,
 'modi gujarati end': 169,
 'gujarati end mod': 85,
 'end mod modi': 64,
 'mod modi listen': 159,
 'modi listen born': 171,
 'listen born september': 129,
 'born september indian': 29,
 'september indian politician': 241,
 'indian politician serving': 111,
 'politician serving th': 203,
 'serving th current': 245,
 'th current prime': 261,
 'current prime minister': 48,
 'prime minister india': 209,
 'minister india since': 153,
 'modi chief': 164,
 'chief minister': 32,
 'minister gujarat': 150,
 'gujarat member': 80,


In [ ]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi listen born september indian politician serving th current prime minister india since'

In [ ]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])

In [ ]:
### TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(ngram_range=(1,1),max_features=10)
X=cv.fit_transform(corpus)

In [ ]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi listen born september indian politician serving th current prime minister india since'

In [ ]:
X[0].toarray()

array([[0.38064993, 0.        , 0.38064993, 0.38064993, 0.        ,
        0.31757459, 0.5871889 , 0.        , 0.        , 0.34593707]])

##WORDTOVEC

In [ ]:
!pip install gensim

In [ ]:
import gensim

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
# references: https://stackoverflow.com/questions/46433778/import-googlenews-vector-negative300-bin

In [ ]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [ ]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
len(wv['man']), wv['man']

(300,
 array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
        -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
         0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
         0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
        -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
        -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
         0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
         0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
         0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
        -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
        -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
        -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
         0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
        -0.00927734, -0.03442383, -0.11523438

In [ ]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [ ]:
wv.most_similar('woman')

[('man', 0.7664012908935547),
 ('girl', 0.7494640946388245),
 ('teenage_girl', 0.7336829304695129),
 ('teenager', 0.6317085027694702),
 ('lady', 0.6288785934448242),
 ('teenaged_girl', 0.6141784191131592),
 ('mother', 0.6076306104660034),
 ('policewoman', 0.6069462299346924),
 ('boy', 0.5975907444953918),
 ('Woman', 0.5770983099937439)]

In [ ]:
wv.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [ ]:
wv.similarity('man', 'king')

0.22942673

In [ ]:
wv.similarity('man', 'woman')

0.76640123

In [ ]:
wv.similarity('kabaddi', 'sports'), wv.similarity('chess', 'sports')

(0.2829672, 0.26091477)

In [ ]:
vec = wv['king'] - wv['man'] + wv['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [ ]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

## Implementing BOW and TFIDF on SMS spam collection dataset


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from posixpath import sep
import pandas as pd

file_path = '/content/drive/MyDrive/SMSSpamCollection.txt'

messages = pd.read_csv(file_path, sep='\t', names=["labels", "message"])

messages

labels                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
messages.shape, messages['message'].loc[451]

((5572, 2), 'hanks lotsly!')

In [ ]:
# data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


In [ ]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [ ]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(2,2))
X = cv.fit_transform(corpus).toarray()
X.shape, X[1]

((5572, 2500), array([0, 0, 0, ..., 0, 0, 0]))

In [ ]:
y = pd.get_dummies(messages['labels'])
y = y.iloc[:, 1].values
y

array([0, 0, 1, ..., 0, 0, 0], dtype=uint8)

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
X_train, y_train

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([0, 0, 0, ..., 1, 0, 0], dtype=uint8))

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [ ]:
# prediction
y_pred = spam_detect_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
score

0.9704035874439462

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98       986
           1       0.80      0.99      0.89       129

    accuracy                           0.97      1115
   macro avg       0.90      0.98      0.93      1115
weighted avg       0.98      0.97      0.97      1115



In [ ]:
# creating the TFIDF model
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range=(2,2))
X = tv.fit_transform(corpus).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train, y_train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([0, 0, 0, ..., 1, 0, 0], dtype=uint8))

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model_1 = MultinomialNB().fit(X_train, y_train)

In [ ]:
y_pred_1 = spam_detect_model_1.predict(X_test)

In [ ]:
score1 = accuracy_score(y_test, y_pred_1)
score1

0.9605381165919282

In [ ]:
print(classification_report(y_pred_1, y_test))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98       999
           1       0.72      1.00      0.84       116

    accuracy                           0.96      1115
   macro avg       0.86      0.98      0.91      1115
weighted avg       0.97      0.96      0.96      1115



In [ ]:
# random forest
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier().fit(X_train, y_train)

In [ ]:
y_pred_rfc = rf_classifier.predict(X_test)
y_pred_rfc

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [ ]:
score_rfc = accuracy_score(y_test, y_pred)
print(score_rfc, '\n', classification_report(y_pred_rfc, y_test))

0.9704035874439462 
               precision    recall  f1-score   support

           0       1.00      0.97      0.98       986
           1       0.79      0.98      0.87       129

    accuracy                           0.97      1115
   macro avg       0.89      0.97      0.93      1115
weighted avg       0.97      0.97      0.97      1115



## Word2Vec Implementation on SMS spam collection dataset

- Gensim has word2vec in it, there are 2 ways of using word2vec
>1.   Pre-Trained Model - eg: Google News 300, etc
>2.   Train your own model

- word2vec can be done using skipgrams/CBOW.

But, if I use google news 300, then for input "I want to eat pizza" would have 5X300 shape as each word would be converted into 1X300 dimension for the google model.

To fix this problem, I can use avgWord2Vec.

avgWord2Vec says, each input feature in the 1X300 in all words will be added and averaged to get just one 1X300 as input for the pre-trained model.

eg: Image 1 in word2vec section.


  

In [ ]:
!pip install gensim

In [ ]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
wv['king'], wv['king'].shape

(array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
        -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
         5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
        -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
         3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
         1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
         1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
         3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
         1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
         3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
         1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
         3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
        -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
        -2.5

train from scratch

In [ ]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
corpus = []

for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z0-9]', ' ', messages['message'][i])
  review = review.lower()
  review = review.split()

  review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


In [ ]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', 'What you doing?how are you?'],
 [0, '', 'Where @'],
 [0, '', 'Can a not?'],
 [0, '', ':) '],
 [0, '', 'What you doing?how are you?'],
 [0, '', ':( but your not here....'],
 [0, '', ':-) :-)']]

In [ ]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry 2 wkly comp win fa cup final tkts 21st may 2005 text fa 87121 receive entry question std txt rate c apply 08452810075over18',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling 3 week word back like fun still tb ok xxx std chgs send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press 9 copy friend callertune',
 'winner valued network customer selected receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobile 11 month u r entitled update latest colour mobile camera free call mobile update co free 08002986030',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6days 16 tsandcs apply reply

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
nltk.download('punkt')
words = []
for sent in corpus:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

words

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

- based on unique words, I will now create my model from scratch

In [ ]:
import gensim
model = gensim.models.Word2Vec(words, window=5, min_count=2) # window is used to understand the context before and after, also used in CBOW
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'go',
 'lt',
 'ok',
 'day',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'text',
 'love',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'make',
 'dear',
 'night',
 'message',
 'well',
 'say',
 'min',
 'thing',
 'much',
 'great',
 'claim',
 'hope',
 'oh',
 'hey',
 'give',
 'number',
 'happy',
 'friend',
 'work',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'ask',
 'said',
 'win',
 'amp',
 'life',
 'cash',
 'yeah',
 'im',
 'tone',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'uk',
 'last',
 'service',
 'thanks',
 'care',
 'com',
 'would',
 'anything',
 'year',
 'also',
 'lol',
 'nokia',
 'every',
 'feel',
 'keep',
 'sure',
 'pick',
 'urgent',
 'contact',
 'sent',


In [ ]:
model.corpus_count, model.epochs

(5565, 5)

In [ ]:
model.wv.similar_by_word('hope')

[('day', 0.9997546076774597),
 ('got', 0.9997356534004211),
 ('like', 0.999727189540863),
 ('thing', 0.9997097849845886),
 ('one', 0.9997075200080872),
 ('back', 0.9996826648712158),
 ('make', 0.9996792078018188),
 ('need', 0.9996783137321472),
 ('friend', 0.9996779561042786),
 ('much', 0.9996772408485413)]

In [ ]:
model.wv['kid'].shape

(100,)

In [ ]:
import numpy as np
def avg_word2vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)

In [ ]:
!pip install tqdm

In [ ]:
from tqdm import tqdm

In [ ]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  're

In [ ]:
words[73]

['performed']

In [ ]:
type(model.wv.index_to_key)

list

In [ ]:
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

  0%|          | 0/5565 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5565/5565 [00:02<00:00, 2530.75it/s]


In [ ]:
type(X)

list

In [ ]:
X_new = np.array(X)

<ipython-input-30-fed0be51dbbf>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_new = np.array(X)


In [ ]:
words[2]

['free',
 'entry',
 'wkly',
 'comp',
 'win',
 'fa',
 'cup',
 'final',
 'tkts',
 'st',
 'may',
 'text',
 'fa',
 'receive',
 'entry',
 'question',
 'std',
 'txt',
 'rate',
 'apply',
 'over']

In [ ]:
X_new[2].shape, X_new[2]

((100,),
 array([-0.10248479,  0.2783449 ,  0.04618497,  0.01330632,  0.00348687,
        -0.35605955,  0.05412712,  0.48851317, -0.14147198, -0.09351552,
        -0.08376164, -0.35718036, -0.05118073,  0.0355558 ,  0.08450152,
        -0.21386828, -0.01967753, -0.33039358, -0.04803643, -0.37236658,
         0.12663953,  0.03448956,  0.09471224, -0.10380013, -0.15704548,
         0.02191695, -0.24832149, -0.24763276, -0.19055453,  0.05642883,
         0.2344474 ,  0.02723299,  0.10091431, -0.10382487, -0.11871665,
         0.2283561 , -0.02013657, -0.26016113, -0.17681816, -0.42239052,
         0.0149795 , -0.25843248,  0.00847882,  0.03844514,  0.19047597,
        -0.12956086, -0.1752181 ,  0.01498757,  0.11340161,  0.15223019,
         0.08954293, -0.2208513 , -0.02820476, -0.03881167, -0.16338412,
         0.11535898,  0.1348682 ,  0.03842919, -0.23156093,  0.00813702,
         0.02571058,  0.12443532, -0.13061845,  0.01514464, -0.26558807,
         0.20540583,  0.09885369,  0.24615

In [ ]:
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['labels'])
y=y.iloc[:,0].values

In [ ]:
X[0].reshape(1,-1).shape

(1, 100)

In [ ]:
df=pd.DataFrame()
for i in range(0,len(X)):
    df=df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)

<ipython-input-35-f72a314a9110>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)


In [ ]:
df['Output']=y
df.head()

0         1         2         3         4         5         6  \
0 -0.109236  0.302274  0.048002  0.012324  0.001952 -0.387220  0.059196   
1 -0.069898  0.199275  0.031443  0.006049  0.001073 -0.253473  0.038124   
2 -0.102485  0.278345  0.046185  0.013306  0.003487 -0.356060  0.054127   
3 -0.131816  0.370988  0.060704  0.017862 -0.000793 -0.477696  0.075158   
4 -0.129657  0.361776  0.058054  0.018022  0.003139 -0.465756  0.076164   

          7         8         9  ...        91        92        93        94  \
0  0.536313 -0.152457 -0.108461  ...  0.138802 -0.071595  0.131380  0.414019   
1  0.355442 -0.100353 -0.074568  ...  0.092983 -0.049447  0.083534  0.280189   
2  0.488513 -0.141472 -0.093516  ...  0.124205 -0.068302  0.115570  0.382038   
3  0.663475 -0.195093 -0.126565  ...  0.174714 -0.087559  0.167649  0.519687   
4  0.642764 -0.185539 -0.121064  ...  0.173491 -0.082117  0.159074  0.500606   

         95        96        97        98        99  Output  
0  0.266146  0.152067 -0.239353  0.073287 -0.044877       1  
1  0.180473  0.106829 -0.159113  0.048834 -0.029650       1  
2  0.251266  0.137923 -0.216573  0.068330 -0.038144       0  
3  0.331514  0.191892 -0.294042  0.090177 -0.066664       1  
4  0.326009  0.185830 -0.283683  0.094334 -0.054643       1  

[5 rows x 101 columns]

In [ ]:
df.dropna(inplace=True)
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [ ]:
X=df
X.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [ ]:
y=df['Output']

In [ ]:
X.shape, y.shape

((5541, 101), (5541,))

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train, y_train

(             0         1         2         3         4         5         6  \
 4178 -0.125819  0.351003  0.054181  0.016399  0.003284 -0.448666  0.065383   
 1756 -0.152109  0.428293  0.080149  0.021355  0.001245 -0.560743  0.088611   
 1523 -0.164593  0.440488  0.067374  0.002755  0.002235 -0.594019  0.087412   
 1624 -0.142971  0.388227  0.067145  0.013549 -0.000148 -0.513043  0.080517   
 4311 -0.054407  0.140524  0.023368  0.006771  0.001130 -0.176349  0.027318   
 ...        ...       ...       ...       ...       ...       ...       ...   
 1629 -0.166962  0.467117  0.075900  0.019486  0.001259 -0.615022  0.096704   
 4342 -0.141785  0.380120  0.068902  0.013372  0.005222 -0.497818  0.079335   
 3299 -0.120163  0.331529  0.058375  0.018642 -0.002041 -0.429521  0.066401   
 572  -0.035871  0.099948  0.015534  0.011920  0.001874 -0.133811  0.014754   
 4436 -0.134149  0.390716  0.065235  0.011252  0.007169 -0.501595  0.080395   
 
              7         8         9  ...        91

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4432, 101), (4432,), (1109, 101), (1109,))

In [ ]:
X_train.columns = X_train.columns.astype(str)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
spam_detection_model_2 = RandomForestClassifier()
spam_detection_model_2.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
X_test.columns = X_test.columns.astype(str)

In [ ]:
y_pred = spam_detection_model_2.predict(X_test)
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9963931469792606


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99       141
           1       1.00      1.00      1.00       968

    accuracy                           1.00      1109
   macro avg       1.00      0.99      0.99      1109
weighted avg       1.00      1.00      1.00      1109

